# Generated by Django 4.1.7 on 2024-02-16 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pfimapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('password', models.CharField(max_length=128, validators=[pfimapp.validators.validate_password])),
                ('email', models.EmailField(error_messages={'unique': 'Este correo electrónico ya está en uso.'}, max_length=50, unique=True, validators=[pfimapp.validators.validate_min_length_correo])),
                ('nacionalidad', models.CharField(max_length=20, validators=[pfimapp.validators.validate_min_length_and_letters])),
                ('numeroDocumento', models.CharField(error_messages={'unique': 'Este DNI ya está en uso.'}, max_length=12, unique=True, validators=[pfimapp.validators.validate_min_numeric_length])),
                ('numeroUbigeoNacimiento', models.CharField(help_text='Ingrese un número de 6 dígitos.', max_length=6, validators=[pfimapp.validators.validate_numeric_length])),
                ('direccion', models.CharField(max_length=50)),
                ('primerNombre', models.CharField(max_length=50, validators=[pfimapp.validators.validate_min_length_and_letters])),
                ('segundoNombre', models.CharField(blank=True, max_length=50, null=True, validators=[pfimapp.validators.validate_min_length_and_letters])),
                ('apellidoPaterno', models.CharField(max_length=50, validators=[pfimapp.validators.validate_min_length_and_letters])),
                ('apellidoMaterno', models.CharField(max_length=50, validators=[pfimapp.validators.validate_min_length_and_letters])),
                ('correoUNI', models.EmailField(blank=True, max_length=50, null=True, unique=True, validators=[pfimapp.validators.validate_min_length_correo])),
                ('telefono', models.CharField(max_length=15, validators=[pfimapp.validators.validate_min_numeric_length])),
                ('fechaNacimiento', models.DateField(blank=True, help_text='Formato: AAAA-MM-DD', null=True, validators=[pfimapp.validators.validate_past_date])),
                ('eliminado', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': '03 - Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoUniPreGrado', models.CharField(blank=True, max_length=10, null=True)),
                ('codigoAlumPFIM', models.CharField(blank=True, max_length=15, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='192.168.1.8', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '09 - Alumnos',
            },
        ),
        migrations.CreateModel(
            name='ConceptoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('eliminado', models.BooleanField(default=False)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='192.168.1.8', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '06 - Conceptos de Pagos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('credito', models.IntegerField()),
                ('eliminado', models.BooleanField(default=False)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='192.168.1.8', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '12 - Cursos',
            },
        ),
        migrations.CreateModel(
            name='DetalleMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retirado', models.BooleanField(default=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='192.168.1.8', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Detalle de Matriculas',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='192.168.1.8', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '13 - Docentes',
            },
        ),
        migrations.CreateModel(
            name='EstadoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('eliminado', models.BooleanField(default=False)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='192.168.1.8', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '08 - Estados Academico',
            },
        ),
        migrations.CreateModel(
            name='EstadoBoletaP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('eliminado', models.BooleanField(default=False)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='192.168.1.8', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '07 - Estados Boletas Pagos',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('eliminado', models.BooleanField(default=False)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='192.168.1.8', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '02 - Estado Civil',
            },
        ),
        migrations.CreateModel(
            name='Maestria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('eliminado', models.BooleanField(default=False)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='192.168.1.8', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '11 - Maestrias',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('eliminado', models.BooleanField(default=False)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='192.168.1.8', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '05 - Periodos',
                'unique_together': {('codigo',)},
            },
        ),
        migrations.CreateModel(
            name='ReporteEcoConceptoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('numeroRecibo', models.CharField(blank=True, max_length=100, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='192.168.1.8', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
                ('conceptoPago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.conceptopago')),
                ('estadoBoletaPago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.estadoboletap')),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('eliminado', models.BooleanField(default=False)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='192.168.1.8', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '04 - Sede',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('eliminado', models.BooleanField(default=False)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='192.168.1.8', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '01 - Tipo de Documentos',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aulaWeb', models.CharField(blank=True, max_length=100, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='192.168.1.8', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.curso')),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.docente')),
                ('maestria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.maestria')),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.periodo')),
            ],
            options={
                'verbose_name_plural': '14 - Secciones',
            },
        ),
        migrations.CreateModel(
            name='ReporteEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='192.168.1.8', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.alumno')),
                ('conceptoPago', models.ManyToManyField(blank=True, through='pfimapp.ReporteEcoConceptoPago', to='pfimapp.conceptopago')),
            ],
            options={
                'verbose_name_plural': '10 - Reportes Economicos',
            },
        ),
        migrations.AddField(
            model_name='reporteecoconceptopago',
            name='reporteEconomico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.reporteeconomico'),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False)),
                ('fechaRegistro', models.DateField(default=django.utils.timezone.now)),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='192.168.1.8', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.alumno')),
                ('seccion', models.ManyToManyField(blank=True, through='pfimapp.DetalleMatricula', to='pfimapp.seccion')),
            ],
            options={
                'verbose_name_plural': '15 - Matriculas',
            },
        ),
        migrations.AddField(
            model_name='docente',
            name='maestria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.maestria'),
        ),
        migrations.AddField(
            model_name='docente',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallematricula',
            name='matricula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.matricula'),
        ),
        migrations.AddField(
            model_name='detallematricula',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.seccion'),
        ),
        migrations.CreateModel(
            name='DefinicionCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('porcentaje', models.IntegerField()),
                ('eliminado', models.BooleanField(default=False)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfimapp.seccion')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Calificaciones',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(blank=True, null=True)),
                ('fecha_calificacion', models.DateField(default=django.utils.timezone.now)),
                ('eliminado', models.BooleanField(default=False)),
                ('definicionCalificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfimapp.definicioncalificacion')),
                ('detalle_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfimapp.detallematricula')),
            ],
            options={
                'verbose_name_plural': 'Calificaciones',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='estadoAcademico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.estadoacademico'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='maestria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.maestria'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='periodoDeIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.periodo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.sede'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='estadoCivil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.estadocivil'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipoDocumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.tipodocumento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='docente',
            unique_together={('usuario', 'maestria')},
        ),
        migrations.AlterUniqueTogether(
            name='alumno',
            unique_together={('usuario', 'maestria')},
        ),
    ]
